spring.application.name=TaskHive

spring.datasource.url=jdbc:postgresql://localhost:5432/taskhive
spring.datasource.username=c0nf1dxnt
spring.datasource.password=

spring.liquibase.enabled=false
spring.jpa.show-sql=true
